# Generated by Django 2.0 on 2018-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.IntegerField(verbose_name='工号')),
                ('member_name', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('member_sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=32, verbose_name='性别')),
                ('member_birthday', models.CharField(max_length=32, verbose_name='出生日期')),
                ('entry_time', models.CharField(max_length=32, verbose_name='入司时间')),
                ('member_company', models.CharField(default='重庆市轨道交通（集团）有限公司', max_length=32, verbose_name='公司')),
                ('member_department', models.CharField(max_length=32, verbose_name='部门')),
                ('member_position', models.CharField(max_length=32, verbose_name='岗位/职务')),
                ('member_level', models.CharField(choices=[('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('中一', '中一'), ('中二', '中二'), ('中三', '中三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('技师', '技师'), ('高级技师', '高级技师')], max_length=32, verbose_name='技能等级')),
                ('political_status', models.CharField(choices=[('中共党员', '中共党员'), ('中共预备党员', '中共预备党员'), ('入党积极分子', '入党积极分子'), ('共青团员', '共青团员'), ('九三学社社员', '九三学社社员'), ('无党派人士', '无党派人士'), ('群众', '群众')], max_length=32, verbose_name='政治面貌')),
                ('member_phone', models.BigIntegerField(verbose_name='联系电话')),
                ('member_email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('member_introduction', models.TextField(verbose_name='员工简介')),
                ('member_other', models.TextField(verbose_name='其它信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('member_photo', models.ManyToManyField(limit_choices_to={'file_tag': '员工照片'}, to='file.File', verbose_name='员工照片')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
    ]
