# Generated by Django 2.0 on 2018-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('member', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, unique=True, verbose_name='班组名称')),
                ('group_location', models.CharField(max_length=32, verbose_name='班组地址')),
                ('group_phone', models.BigIntegerField(verbose_name='班组电话')),
                ('group_introduction', models.TextField(verbose_name='班组简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('group_equipment', models.ManyToManyField(to='equipment.Equipment', verbose_name='班组设备')),
                ('group_member', models.ManyToManyField(to='member.Member', verbose_name='班组成员')),
                ('group_other_information', models.ManyToManyField(limit_choices_to={'file_tag': '其它附件'}, related_name='班组信息其它附件', to='file.File', verbose_name='其它附件')),
                ('group_photo', models.ManyToManyField(limit_choices_to={'file_tag': '班组照片'}, related_name='班组照片', to='file.File', verbose_name='班组照片')),
            ],
            options={
                'verbose_name': '班组信息',
                'verbose_name_plural': '班组信息',
            },
        ),
    ]
