# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value1', models.CharField(max_length=50)),
                ('value2', models.CharField(max_length=50)),
                ('value3', models.CharField(max_length=50)),
                ('value4', models.CharField(max_length=50)),
                ('value5', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 18, 197079))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 18, 197079))),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 18, 197079))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 18, 197079))),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
