# Generated by Django 2.0.1 on 2018-04-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('temperature', models.SmallIntegerField(verbose_name='温度')),
                ('humidity', models.SmallIntegerField(verbose_name='湿度')),
                ('location', models.CharField(max_length=64, verbose_name='位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '传感器数据',
                'verbose_name': '传感器数据',
            },
        ),
    ]
