# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 20, 233196)),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 20, 233196)),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 20, 232196)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 19, 26, 20, 232196)),
        ),
    ]
