# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datetime',
        ),
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
