# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170910_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.IntegerField(choices=[(0, '好'), (1, '坏')]),
        ),
    ]
