# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170910_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('好', '好'), ('坏', '坏')], max_length=50),
        ),
    ]
