# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170910_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 1, 10, 16, 880579)),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 1, 10, 16, 880579)),
        ),
    ]
