# Generated by Django 2.0 on 2018-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('web_content', models.TextField(max_length=255, verbose_name='内容描述')),
                ('web_status', models.CharField(choices=[('打开', '打开'), ('关闭', '关闭')], max_length=32, verbose_name='开关')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网站信息',
                'verbose_name_plural': '网站信息',
            },
        ),
    ]
