# Generated by Django 2.0 on 2018-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32, unique=True, verbose_name='文件名称')),
                ('file_tag', models.CharField(choices=[('班组照片', '班组照片'), ('员工照片', '员工照片'), ('设备照片', '设备照片'), ('其它附件', '其它附件')], max_length=32, verbose_name='文件标签')),
                ('file_upload', models.FileField(upload_to='static/file/%Y%m%d/', verbose_name='文件信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '附件信息',
                'verbose_name_plural': '附件信息',
            },
        ),
    ]
